exports.HMData = {
  User_Details: [
    {
      UserID: 1,
      FName: "John",
      LName: "Doe",
      Email: "john.doe@example.com",
      Mobile: "1234567890",
      DOB: "1985-02-15",
      Gender: "male",
    },
    {
      UserID: 2,
      FName: "Jane",
      LName: "Smith",
      Email: "jane.smith@example.com",
      Mobile: "1234567891",
      DOB: "1990-06-21",
      Gender: "female",
    },
    {
      UserID: 3,
      FName: "Alice",
      LName: "Johnson",
      Email: "alice.johnson@example.com",
      Mobile: "1234567892",
      DOB: "1982-07-13",
      Gender: "female",
    },
    {
      UserID: 4,
      FName: "Bob",
      LName: "Brown",
      Email: "bob.brown@example.com",
      Mobile: "1234567893",
      DOB: "1988-05-09",
      Gender: "male",
    },
    {
      UserID: 5,
      FName: "Charlie",
      LName: "Davis",
      Email: "charlie.davis@example.com",
      Mobile: "1234567894",
      DOB: "1995-01-22",
      Gender: "male",
    },
    {
      UserID: 6,
      FName: "David",
      LName: "Wilson",
      Email: "david.wilson@example.com",
      Mobile: "1234567895",
      DOB: "1992-03-11",
      Gender: "male",
    },
    {
      UserID: 7,
      FName: "Eve",
      LName: "Evans",
      Email: "eve.evans@example.com",
      Mobile: "1234567896",
      DOB: "1987-10-03",
      Gender: "female",
    },
    {
      UserID: 8,
      FName: "Frank",
      LName: "Harris",
      Email: "frank.harris@example.com",
      Mobile: "1234567897",
      DOB: "1989-12-19",
      Gender: "male",
    },
    {
      UserID: 9,
      FName: "George",
      LName: "Lee",
      Email: "george.lee@example.com",
      Mobile: "1234567898",
      DOB: "1993-09-14",
      Gender: "male",
    },
    {
      UserID: 10,
      FName: "Helen",
      LName: "Moore",
      Email: "helen.moore@example.com",
      Mobile: "1234567899",
      DOB: "1991-11-07",
      Gender: "female",
    },
    {
      UserID: 11,
      FName: "Alice",
      LName: "Green",
      Email: "alice.green@example.com",
      Mobile: "1234567880",
      DOB: "1985-08-15",
      Gender: "female",
    },
    {
      UserID: 12,
      FName: "Bob",
      LName: "Smith",
      Email: "bob.smith@example.com",
      Mobile: "1234567881",
      DOB: "1992-01-15",
      Gender: "male",
    },
    {
      UserID: 13,
      FName: "Carol",
      LName: "White",
      Email: "carol.white@example.com",
      Mobile: "1234567882",
      DOB: "1980-11-25",
      Gender: "female",
    },
    {
      UserID: 14,
      FName: "David",
      LName: "Black",
      Email: "david.black@example.com",
      Mobile: "1234567883",
      DOB: "1975-04-12",
      Gender: "male",
    },
    {
      UserID: 15,
      FName: "Eve",
      LName: "Brown",
      Email: "eve.brown@example.com",
      Mobile: "1234567884",
      DOB: "1988-07-30",
      Gender: "female",
    },
    {
      UserID: 16,
      FName: "Henry",
      LName: "Miller",
      Email: "henry.miller@example.com",
      Mobile: "123456789A",
      DOB: "1990-02-25",
      Gender: "male",
    },
    {
      UserID: 17,
      FName: "Ivy",
      LName: "Clark",
      Email: "ivy.clark@example.com",
      Mobile: "123456789B",
      DOB: "1986-09-05",
      Gender: "female",
    },
    {
      UserID: 18,
      FName: "Jack",
      LName: "Taylor",
      Email: "jack.taylor@example.com",
      Mobile: "123456789C",
      DOB: "1994-12-15",
      Gender: "male",
    },
    {
      UserID: 19,
      FName: "Karen",
      LName: "Lewis",
      Email: "karen.lewis@example.com",
      Mobile: "123456789D",
      DOB: "1989-07-21",
      Gender: "female",
    },
    {
      UserID: 20,
      FName: "Luke",
      LName: "Walker",
      Email: "luke.walker@example.com",
      Mobile: "123456789E",
      DOB: "1987-05-11",
      Gender: "male",
    },
  ],

  Owners: [
    { Owner_ID: 1, UserID: 1 },
    { Owner_ID: 2, UserID: 2 },
    { Owner_ID: 3, UserID: 3 },
    { Owner_ID: 4, UserID: 4 },
    { Owner_ID: 5, UserID: 5 },
  ],

  Hotels: [
    {
      Hotel_ID: 1,
      HName: "Sunshine Inn",
      Location: "123 Beach Ave, Mumbai, Maharashtra",
      Owner_ID: 1,
      City: "Mumbai",
    },
    {
      Hotel_ID: 2,
      HName: "Mountain Retreat",
      Location: "789 Hilltop Rd, Bangalore, Karnataka",
      Owner_ID: 2,
      City: "Bangalore",
    },
    {
      Hotel_ID: 3,
      HName: "City Lights",
      Location: "456 Downtown St, Delhi",
      Owner_ID: 3,
      City: "Delhi",
    },
    {
      Hotel_ID: 4,
      HName: "Oceanview Lodge",
      Location: "456 Ocean Drive, Chennai, Tamil Nadu",
      Owner_ID: 4,
      City: "Chennai",
    },
    {
      Hotel_ID: 5,
      HName: "Desert Oasis",
      Location: "123 Desert Rd, Jaipur, Rajasthan",
      Owner_ID: 5,
      City: "Jaipur",
    },
  ],

  Services: [
    {
      Service_ID: 1,
      Service_Name: "Room Cleaning",
      Service_Desc: "Daily room cleaning service",
      Price: 30,
    },
    {
      Service_ID: 2,
      Service_Name: "Breakfast",
      Service_Desc: "Buffet breakfast service",
      Price: 20,
    },
    {
      Service_ID: 3,
      Service_Name: "Laundry",
      Service_Desc: "Laundry and dry cleaning service",
      Price: 50,
    },
    {
      Service_ID: 4,
      Service_Name: "Spa",
      Service_Desc: "Relaxing spa services",
      Price: 100,
    },
  ],

  Employees: [
    { Emp_ID: 1, UserID: 6, Hotel_ID: 1, Service_ID: 1 },
    { Emp_ID: 2, UserID: 7, Hotel_ID: 1, Service_ID: 2 },
    { Emp_ID: 3, UserID: 8, Hotel_ID: 2, Service_ID: 3 },
    { Emp_ID: 4, UserID: 9, Hotel_ID: 2, Service_ID: 4 },
    { Emp_ID: 5, UserID: 10, Hotel_ID: 3, Service_ID: 1 },
    { Emp_ID: 6, UserID: 11, Hotel_ID: 3, Service_ID: 1 },
    { Emp_ID: 7, UserID: 12, Hotel_ID: 4, Service_ID: 2 },
    { Emp_ID: 8, UserID: 13, Hotel_ID: 4, Service_ID: 3 },
    { Emp_ID: 9, UserID: 14, Hotel_ID: 5, Service_ID: 4 },
    { Emp_ID: 10, UserID: 15, Hotel_ID: 5, Service_ID: 1 },
  ],

  Customers: [
    { Customer_ID: 1, UserID: 16 },
    { Customer_ID: 2, UserID: 17 },
    { Customer_ID: 3, UserID: 18 },
    { Customer_ID: 4, UserID: 19 },
    { Customer_ID: 5, UserID: 20 },
  ],

  Rooms: [
    {
      Room_ID: 1,
      Hotel_ID: 1,
      Room_No: "101",
      Room_Type: "Single",
      Price: 100,
      Room_Status: false,
    },
    {
      Room_ID: 2,
      Hotel_ID: 1,
      Room_No: "102",
      Room_Type: "Double",
      Price: 150,
      Room_Status: true,
    },
    {
      Room_ID: 3,
      Hotel_ID: 2,
      Room_No: "201",
      Room_Type: "Single",
      Price: 120,
      Room_Status: false,
    },
    {
      Room_ID: 4,
      Hotel_ID: 2,
      Room_No: "202",
      Room_Type: "Double",
      Price: 180,
      Room_Status: true,
    },
    {
      Room_ID: 5,
      Hotel_ID: 3,
      Room_No: "301",
      Room_Type: "Suite",
      Price: 250,
      Room_Status: false,
    },
    {
      Room_ID: 6,
      Hotel_ID: 3,
      Room_No: "302",
      Room_Type: "Suite",
      Price: 250,
      Room_Status: true,
    },
    {
      Room_ID: 7,
      Hotel_ID: 4,
      Room_No: "103",
      Room_Type: "Single",
      Price: 110,
    },
    {
      Room_ID: 8,
      Hotel_ID: 4,
      Room_No: "104",
      Room_Type: "Double",
      Price: 160,
      Room_Status: true,
    },
    {
      Room_ID: 9,
      Hotel_ID: 5,
      Room_No: "303",
      Room_Type: "Suite",
      Price: 270,
      Room_Status: false,
    },
    {
      Room_ID: 10,
      Hotel_ID: 5,
      Room_No: "304",
      Room_Type: "Suite",
      Price: 270,
      Room_Status: true,
    },
  ],

  Room_Employee_Map: [
    { REM_ID: 1, Employee_ID: 1, Room_ID: 1 },
    { REM_ID: 2, Employee_ID: 2, Room_ID: 2 },
    { REM_ID: 3, Employee_ID: 3, Room_ID: 3 },
    { REM_ID: 4, Employee_ID: 4, Room_ID: 4 },
    { REM_ID: 5, Employee_ID: 5, Room_ID: 5 },
    { REM_ID: 6, Employee_ID: 6, Room_ID: 6 },
    { REM_ID: 7, Employee_ID: 7, Room_ID: 7 },
    { REM_ID: 8, Employee_ID: 8, Room_ID: 8 },
    { REM_ID: 9, Employee_ID: 9, Room_ID: 9 },
    { REM_ID: 10, Employee_ID: 10, Room_ID: 10 },
  ],

  Bookings: [
    {
      Booking_ID: 1,
      Room_ID: 1,
      Customer_ID: 1,
      Total_Amount: 150,
      Booking_Date: "2024-07-25",
      Check_In_Date: "2024-08-01",
      Check_Out_Date: "2024-08-05",
    },
    {
      Booking_ID: 2,
      Room_ID: 2,
      Customer_ID: 2,
      Total_Amount: 300,
      Booking_Date: "2024-07-27",
      Check_In_Date: "2024-08-03",
      Check_Out_Date: "2024-08-07",
    },
    {
      Booking_ID: 3,
      Room_ID: 3,
      Customer_ID: 3,
      Total_Amount: 250,
      Booking_Date: "2024-07-28",
      Check_In_Date: "2024-08-04",
      Check_Out_Date: "2024-08-08",
    },
    {
      Booking_ID: 4,
      Room_ID: 4,
      Customer_ID: 4,
      Total_Amount: 330,
      Booking_Date: "2024-07-30",
      Check_In_Date: "2024-08-05",
      Check_Out_Date: "2024-08-09",
    },
    {
      Booking_ID: 5,
      Room_ID: 5,
      Customer_ID: 5,
      Total_Amount: 270,
      Booking_Date: "2024-07-31",
      Check_In_Date: "2024-08-06",
      Check_Out_Date: "2024-08-10",
    },
    {
      Booking_ID: 6,
      Room_ID: 1,
      Customer_ID: 1,
      Total_Amount: 150,
      Booking_Date: "2024-07-25",
      Check_In_Date: "2024-08-01",
      Check_Out_Date: "2024-08-05",
    },
    {
      Booking_ID: 7,
      Room_ID: 2,
      Customer_ID: 2,
      Total_Amount: 150,
      Booking_Date: "2024-08-02",
      Check_In_Date: "2024-08-08",
      Check_Out_Date: "2024-08-15",
    },
  ],
};
